name: Bearer Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Escaneo con formato SARIF para GitHub Security
      - name: Run Bearer Security Scan
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: results.sarif
          skip-path: 
            - node_modules
            - public
            - reports
            - .next
            - .git
          scanner: sast,secrets
          severity: critical,high,medium,low,warning
          diff: ${{ github.event_name == 'pull_request' }}
          exit-code: 0

      # Upload SARIF results to GitHub Security tab
      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
