name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Repository URL to scan'
        required: true
        default: 'https://github.com/Harmeto/menv_auth'
      branch:
        description: 'Branch to scan'
        required: false
        default: 'master'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  scan-demo:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Bearer Security Scan
        uses: bearer/bearer-action@v2
        with:
          path: '.'
          format: html
          output: 'public/demo-scan-report.html'
          scanner: sast,secrets
          severity: critical,high,medium,low,warning
          
      - name: Commit and push scan results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/demo-scan-report.html
          git commit -m "Update demo scan report" || exit 0
          git push

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
